### ISSUE TITLE
Meta tags

### ISSUE THREAD

**Issue by Eonasdan** [Eonasdan/static-site-generator#24]
- [x] Author needs to be updated like the other tags
  - [x] `<meta name="article:author" content=""/>`
  - [x] ` <meta name="author" content="Jonathan Peterson"/>` (linkedin is stupid)
- [x] I fixed the social meta tags in my blog, need to bring this back
